
name: Build and Upload Android Release aab 

# on:
#   release:
#     types: [created]

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install

      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEYSTORE }}
 
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > ./android/app/com.kchen.Splitsies.keystore

      - name: Decode Google Services
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_ANDROID_BASE64_PRODUCTION }}
 
        run: |
           echo $GOOGLE_SERVICES > gs.android.json
           base64 -d gs.android.json > ./android/app/google-services.json

      - name: Restore gradle.properties
        env:
            GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
            mkdir -p ~/.gradle/
            echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
            echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Build .aab
        run: |
          cd android && ./gradlew bundleProductionRelease

      - name: Upload .aab Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-production-release.aab
          path: android/app/build/outputs/bundle/productionRelease/

      - name: Decode Play Store Service Account
        env:
          PLAYSTORE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
            echo $PLAYSTORE_SERVICE_ACCOUNT_JSON_BASE64 > sa.base64
            base64 -d sa.base64 > service_account.json

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.kchen.Splitsies
          releaseFiles: android/app/build/outputs/bundle/productionRelease/app-production-release.aab
          track: beta
          whatsNewDirectory: whatsnew/