
name: Build Android Dev-PR aab 

on:
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install

      - name: Decode Keystore
        env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEYSTORE }}
 
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > ./android/app/com.kchen.Splitsies.keystore

      - name: Decode Google Services
        env:
            GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_ANDROID_BASE64_DEV_PR }}
 
        run: |
           echo $GOOGLE_SERVICES > gs.android.json
           base64 -d gs.android.json > ./android/app/google-services.json

      - name: Restore gradle.properties
        env:
            GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
            mkdir -p ~/.gradle/
            echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
            echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Build .aab
        run: |
          cd android && ./gradlew bundleDevprRelease

      - name: Upload .aab Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-devpr-release.aab
          path: android/app/build/outputs/bundle/devprRelease/